// packages/react/src/stories/Button.tsx
import * as React from 'react'

import {tw} from 'twind'

export function Button({name, active = false, ...props}) {
  return (
    <div>
      <button
        className={tw`py-2 px-4 ${
          active ? 'bg-gray-500' : ''
        } hover:bg-gray-700 rounded-md`}
        {...props}
      >
        {name}
      </button>
    </div>
  )
}

// packages/vue/src/stories/Button.vue
<template>
  <button
    :class="
      tw([
        `py-2 px-4 ${active ? 'bg-gray-500' : ''} hover:bg-gray-700 rounded-md`,
      ])
    "
    @click="$emit('click')"
  >
    {{ name }}
  </button>
</template>

<script>
import {tw} from 'twind'

export default {
  name: 'dev-toolbar',

  props: {
    name: {
      type: String,
      required: true,
    },
    active: {
      type: Boolean,
      default: false,
    },
  },

  methods: {
    tw,
  },
}
</script>
